[package]
name = "qextra"
version = "0.1.0"

[dependencies]
lito-qt = { version = "0.1.1" }
rstd-std = { version = "0.1.5", pub = true }
rstd-cppstd = { version = "0.1.5", pub = true }
ncrequest = { git = "https://github.com/hypengw/ncrequest.git", pub = true }
wavsen = { git = "https://github.com/hypengw/wavsen.git", pub = true }

[lib]
name = "qextra"
module = "qextra"
archive = "qextra"

[usage]
public-include-directories = ["include"]
private-include-directories = ["src", "include/QExtra"]

[external-dependencies.cmake.qt6]
package = "Qt6"
components = [
  "Core",
  "DBus",
  "Network",
  "Protobuf",
  "ProtobufQuick",
  "ProtobufWellKnownTypes",
  "Quick",
  "QuickPrivate",
  "GuiPrivate",
  "Qml",
]
targets = [
  { name = "Qt6::Core", pub = true },
  { name = "Qt6::DBus", pub = true },
  { name = "Qt6::Protobuf", pub = true },
  { name = "Qt6::Quick", pub = true },
  { name = "Qt6::QuickPrivate" },
  { name = "Qt6::GuiPrivate" },
  { name = "Qt6::Network" },
]
host-tools = [
  { name = "moc", target = "Qt6::moc" },
  { name = "rcc", target = "Qt6::rcc" },
  { name = "qmltyperegistrar", target = "Qt6::qmltyperegistrar" },
]

[[test]]
name = "qextra-tests"
sources = [
  "test/main.cpp",
  "test/image.cpp",
  "test/image_service.cpp",
  "test/image_network.cpp",
  "test/image_playback.cpp",
  "test/kstore.cpp",
]
