[package]
name = "qextra"
version = "0.1.0"

[dependencies.lito-qt]
builtin = "qt"

[lib]
name = "qextra"
module = "qextra"
archive = "qextra"
sources = [
  "src/qt.cppm",
  "src/mod.cppm",
  "src/kstore.cppm",
  "src/async.cppm",
  "src/helper.cppm",
  "src/bindable.cppm",
  "src/global_static.cppm",
  "src/qml_network.cppm",
  "src/query.cppm",
  "src/select_storage.cppm",
  "src/task.cppm",
  "src/executor.cppm",
  "src/watcher.cppm",
  "src/async.cpp",
  "src/global_static.cpp",
  "src/qml_network.cpp",
  "src/query.cpp",
  "src/select_storage.cpp",
  "src/kstore/share_store.cpp",
  "src/kstore/moc.cpp",
  "src/kstore/meta_role.cpp",
  "src/kstore/meta_utils.cpp",
  "src/kstore/gadget_model.cpp",
  "src/kstore/meta_list_model.cpp",
  "src/kstore/qtable_proxy_model.cpp",
  "src/kstore/qunion_list_model.cpp",
]

[usage]
public-include-directories = ["include"]
private-include-directories = ["src"]

[dependencies.rstd-std]
git = "https://github.com/litocpp/rstd.git"
visibility = "public"

[dependencies.rstd-cppstd]
git = "https://github.com/litocpp/rstd.git"
visibility = "public"

[dependencies.ncrequest]
git = "https://github.com/hypengw/ncrequest.git"
visibility = "public"

[external-dependencies.cmake.qt6]
package = "Qt6"
components = [
  "Core",
  "DBus",
  "Network",
  "Protobuf",
  "ProtobufQuick",
  "ProtobufWellKnownTypes",
  "Quick",
  "Qml",
]
targets = [
  { name = "Qt6::Core", visibility = "public" },
  { name = "Qt6::DBus", visibility = "public" },
  { name = "Qt6::Protobuf", visibility = "public" },
  { name = "Qt6::Quick", visibility = "public" },
  { name = "Qt6::Network", visibility = "private" },
]
host-tools = [{ name = "moc", target = "Qt6::moc" }]
